apiVersion: apps/v1
kind: Deployment
metadata:
  name: apexpos-backend
  namespace: apexpos
  labels:
    app: apexpos-backend
spec:
  replicas: 1               # Single replica for free tier (limited RAM)
  selector:
    matchLabels:
      app: apexpos-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: apexpos-backend
    spec:
      containers:
        - name: backend
          image: tharusha69/apexpos-backend:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              memory: "128Mi"     # Conservative for t3.micro
              cpu: "100m"
            limits:
              memory: "256Mi"     # Hard limit
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
