apiVersion: v1
kind: Service
metadata:
  name: apexpos-backend-svc
  namespace: apexpos
spec:
  type: NodePort             # NodePort is free (no LoadBalancer cost)
  selector:
    app: apexpos-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500        # Accessible at <EC2-IP>:30500
